flowchart BT
subgraph OreSat
subgraph controller[Controller]
c_id[OLAF Interface]
end
bus(CAN Bus)
chip1(Chip 1)
chip2(Chip 2)

c_id---bus
bus---chip1
bus---chip2
chip1---bus
chip2---bus
bus---c_id
end

subgraph GroundStation
subgraph container1 [YAMCS Container]
server1[YAMCS Server]
end
end

server1-->|EDL|c_id
c_id-->|EDL| server1
OreSat-->|Status Updates| GroundStation
