flowchart BT
subgraph OreSat
subgraph controller[C3]
c_id[OLAF Interface]
end
bus(CAN Bus)
card1(Card 1)
card2(Card 2)

c_id---bus
bus---card1
bus---card2
card1---bus
card2---bus
bus---c_id
end

subgraph GroundStation
subgraph container1 [YAMCS Container]
server1[YAMCS Server]
end
end

server1-->|EDL|c_id
c_id-->|EDL| server1
OreSat-->|Beacon| GroundStation
